[project]
authors = ["Michiel Cottaar <MichielCottaar@protonmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "MT-and-permeability-effect-on-two-compartment-dMRI-WM-model"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]
julia-notebook = 'julia --project=. -e "using IJulia; notebook(; dir=\".\")"'

[dependencies]

[feature.python.dependencies]
numpy = "*"
scipy = "*"
jupyter = "*"
pandas = "*"
matplotlib = "*"

[feature.python.tasks]
python-notebook = "jupyter notebook"

[feature.julia.dependencies]
julia = "1.10.4"

[feature.julia.tasks]
julia2-notebook = 'julia --project=. -e "using IJulia; notebook()"'

[environments]
python = ["python"]
julia = ["julia"]
